codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "*/_deps/*"
  - "*/tests/*"
  - "/usr/*"
  - "*/build/*"
  - "*/CMakeFiles/*"

flags:
  unittests:
    paths:
      - engine/src
      - engine/include

